steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA",
        "--region",
        "$_DEPLOY_REGION",
      ]
    - name: "gcr.io/cloud-builders/npm"
    entrypoint: npx
    env:
      - DATABASE_URL=$_DATABASE_URL
    args:
      - "prisma"
      - "migrate"
      - "deploy"
      
images: ["gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"]
# "--build-arg", "REMIX_TOKEN=$_REMIX_TOKEN"

# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/${DATABASE_URL}/versions/latest
#       env: DATABASE_URL
